=== jajasuperman/FunnyBlog/xml/erabiltzaileak.dtd
<!DOCTYPE erabiltzaileak [
<!ELEMENT erabiltzaileak (erabiltzailea)*>
<!ELEMENT erabiltzailea (Erabiltzaile, Emaila, Pasahitza)>
<!ELEMENT Erabiltzaile (#PCDATA)>
<!ELEMENT Emaila (#PCDATA)>
<!ELEMENT Pasahitza (#PCDATA)>
]>

=== jajasuperman/FunnyBlog/xml/erabiltzaileak.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE erabiltzaileak SYSTEM "erabiltzaileak.dtd">
<erabiltzaileak>
  <erabiltzailea>
    <Erabiltzaile>Thadah</Erabiltzaile>
    <Emaila>a</Emaila>
    <Pasahitza>a</Pasahitza>
  </erabiltzailea>
  <erabiltzailea>
    <Erabiltzaile>a</Erabiltzaile>
    <Emaila>a123456</Emaila>
    <Pasahitza>123456</Pasahitza>
  </erabiltzailea>
  <erabiltzailea>
    <Erabiltzaile>eeee</Erabiltzaile>
    <Emaila>eeee@gmail.com</Emaila>
    <Pasahitza>123456</Pasahitza>
  </erabiltzailea>
  <erabiltzailea>
    <Erabiltzaile>❤ ☀ ☆ ☂ ☻ ♞ ☯ ☭ ☢</Erabiltzaile>
    <Emaila>web000@ehu.es</Emaila>
    <Pasahitza>❤ ☀ ☆ ☂ ☻ ♞ ☯ ☭ ☢</Pasahitza>
  </erabiltzailea>
</erabiltzaileak>
